language: php

php:
  - '5.6'
  - '7.0'

before_script:
  - composer require codacy/coverage

script:
 - mkdir -p build/logs
 - phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
 - export CODACY_PROJECT_TOKEN
 - php vendor/bin/codacycoverage clover build/logs/clover.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.0'

# whitelist
branches:
  only:
    - develop
    - stable