language: php

php:
  - '5.6'
  - '7.0'
  
before_script:
  - composer require satooshi/php-coveralls:~0.6@stable

script:
 - phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml
 - mkdir -p build/logs
 
after_script:
 - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.0'
